-- Run this in Supabase → SQL Editor.

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text,
  company text,
  title text,
  email text,
  phone text,
  company_guess text,
  notes text,
  photo_path text,
  owner text
);

create index if not exists contacts_created_at_idx on public.contacts (created_at desc);

-- Storage bucket for badge photos (private; signed URLs served by the API).
insert into storage.buckets (id, name, public)
values ('badges', 'badges', false)
on conflict (id) do nothing;
